PracticaMvcCore2Iniciales/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2.Extensions;
using PracticaMvcCore2.Filters;
using PracticaMvcCore2.Models;
using PracticaMvcCore2.Repositories;
using System.Data;

namespace PracticaMvcCore2.Controllers
{
    public class LibrosController : Controller
    {
        private RepositoryLibros repo;

        public LibrosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {

            List<Libro> libros = await this.repo.GetLibrosAsync();
            return View(libros);

        }
        public async Task<IActionResult> LibrosGenero(int idgenero)
        {
            List<Libro> librosGen = await this.repo.GetLibrosGeneroAsync(idgenero);
            return View(librosGen);

        }

        public async Task<IActionResult> Details(int idlibro)
        {

            Libro libro = await this.repo.GetDetailsLibroAsync(idlibro);

            return View(libro);
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Carrito(int? idadded)
        {
            if (idadded != null)
            {
                List<Libro> librosCarrito;
                if (HttpContext.Session.GetObject<List<Libro>>("CARRITO") == null)
                {
                    librosCarrito = new List<Libro>();
                }
                else
                {
                    librosCarrito = HttpContext.Session.GetObject<List<Libro>>("CARRITO");
                }
                Libro libro = await this.repo.GetDetailsLibroAsync(idadded.Value);
                librosCarrito.Add(libro);
                HttpContext.Session.SetObject("CARRITO", librosCarrito);
            }

            return RedirectToAction("Index");
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> VerCarrito(int? ideliminar)
        {
            List<Libro> listaLibros = HttpContext.Session.GetObject<List<Libro>>("CARRITO");

            if (ideliminar != null)
            {
                Libro libro = listaLibros.Find(z => z.IdLibro == ideliminar.Value);

                listaLibros.Remove(libro);

                if (listaLibros.Count == 0)
                {

                    HttpContext.Session.Remove("CARRITO");

                }
                else
                {
                    //almacenamos de nuevo los datos en session
                    HttpContext.Session.SetObject("CARRITO", listaLibros);
                }

            }
            listaLibros = HttpContext.Session.GetObject<List<Libro>>("CARRITO");

            return View(listaLibros);
        }
        [AuthorizeUsuarios]
        public IActionResult PerfilUsuario()
        {
            return View();
        }

        [AuthorizeUsuarios]

        public async Task<IActionResult> Pedidos()
        {
            int idUsuario = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);

            List<VistaPedidos> pedidos = this.repo.GetVistaPedidoUsuario(idUsuario);

            return View(pedidos);

        }

        [AuthorizeUsuarios]

        public async Task<IActionResult> FinalizarCompra()
        {
            List<Libro> carrito = HttpContext.Session.GetObject<List<Libro>>("CARRITO");
            if (carrito != null)
            {
                int idUser = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);
                this.repo.InsertarPedido(carrito,idUser);
                HttpContext.Session.Remove("CARRITO");
                return RedirectToAction("Pedidos");
            }
            else
            {
                ViewData["MENSAJE"] = "No puedes comprar nada";
            }
            return View("Pedidos");

        }
    }
}

PracticaMvcCore2Iniciales/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2.Repositories;
using System.Numerics;
using System.Security.Claims;
using PracticaMvcCore2.Models;

namespace PracticaMvcCore2.Controllers
{
    public class ManagedController : Controller
    {
        private RepositoryLibros repo;
        public ManagedController(RepositoryLibros repo)
        {
            this.repo = repo;
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Login(string email, string password)
        {

            Usuario user = await this.repo.LogInUsuarioAsync(email, password);

            if (user != null)
            {
                //SEGURIDAD
                ClaimsIdentity identity =
                    new ClaimsIdentity(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        ClaimTypes.Name, ClaimTypes.Role);
                //CREAMOS EL CLAIM PARA EL NOMBRE (APELLIDO)
                Claim claimName =
                    new Claim(ClaimTypes.Name, user.Nombre);
                identity.AddClaim(claimName);
                Claim claimId =
                    new Claim(ClaimTypes.NameIdentifier, user.IdUsuario.ToString());
                identity.AddClaim(claimId);
                Claim claimIdUsuario =
                    new Claim("IdUsuario", user.IdUsuario.ToString());
                identity.AddClaim(claimIdUsuario);
                Claim claimEmail =
                    new Claim("Email", user.Email);
                identity.AddClaim(claimEmail);
                Claim claimApellidos =
                    new Claim("Apellidos", user.Apellidos);
                identity.AddClaim(claimApellidos);
                Claim claimPass =
                    new Claim("Pass", user.Password);
                identity.AddClaim(claimPass);
                Claim claimFoto =
                    new Claim("Foto", user.Foto);
                identity.AddClaim(claimFoto);



                //COMO POR AHORA NO VOY A UTILIZAR NI SE UTILIZAR ROLES
                //NO LO INCLUIMOS
                ClaimsPrincipal userPrincipal =
                    new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    userPrincipal);
                //LO VAMOS A LLEVAR A UNA VISTA QUE TODAVIA NO TENEMOS
                //QUE SERA EL PERFIL DEL EMPLEADO
                return RedirectToAction("PerfilUsuario", "Libros");

            }
            else
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }

        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Libros");
        }

        public IActionResult ErrorAcceso()
        {
            return View();
        }

    }
}

PracticaMvcCore2Iniciales/Views/Shared/_Layout.cshtml
@using PracticaMvcCore2.Extensions
@using PracticaMvcCore2.Models
﻿@{

    List<Libro>libroslista = Context.Session.GetObject<List<Libro>>("CARRITO");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMvcCore2Iniciales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMvcCore2Iniciales.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaMvcCore2Iniciales</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                        </li>
                        @await Component.InvokeAsync("MenuGeneros")
                        @if (libroslista != null)
                        {
                            <li class="nav-item">
                                <span>
                                    Libros: @libroslista.Count
                                </span>
                            </li>

                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="VerCarrito">Ver Carrito</a>
                        </li>
                        <partial name="_MenuUsuario">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PracticaMvcCore2Iniciales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaMvcCore2Iniciales/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated == false)
{
    //EFECTO OPTICO DEL LOGIN
    <li class="nav-item">
        <a asp-controller="Managed"
           asp-action="Login"
           class="nav-link">
            Log In
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="Managed"
           asp-action="Logout"
           class="nav-link">
            Log out <span style="color:blue">
                @Context.User.Identity.Name
            </span>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Libros"
           asp-action="PerfilUsuario"
           class="nav-link">
            Mi perfil
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Libros"
           asp-action="Pedidos"
           class="nav-link">
            Mis Pedidos
        </a>
    </li>
}