PracticaMvcCore2Iniciales/Models/Libro.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaMvcCore2.Models
{
    [Table("LIBROS")]
    public class Libro
    {
        [Key]
        [Column("IDLIBRO")]
        public int IdLibro { get; set; }
        [Column("TITULO")]
        public string Titulo { get; set; }
        [Column("AUTOR")]
        public string Autor { get; set; }
        [Column("EDITORIAL")]
        public string Editorial { get; set; }
        [Column("PORTADA")]
        public string Portada { get; set; }
        [Column("RESUMEN")]
        public string Resumen { get; set; }
        [Column("PRECIO")]
        public int Precio { get; set; }
        [Column("IDGENERO")]
        public int IdGenero { get; set; }
    }
}

PracticaMvcCore2Iniciales/Models/Pedido.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaMvcCore2.Models
{
    [Table("PEDIDOS")]
    public class Pedido
    {
        [Key]
        [Column("IDPEDIDO")]
        public int IdPedido { get; set; }
        [Column("IDFACTURA")]
        public int IdFactura { get; set; }
        [Column("FECHA")]
        public DateTime Fecha { get; set; }
        [Column("IDLIBRO")]
        public int IdLibro { get; set; }
        [Column("IDUSUARIO")]
        public int IdUsuario { get; set; }
        [Column("CANTIDAD")]
        public int Cantidad { get; set; }
    }
}

PracticaMvcCore2Iniciales/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2.Extensions;
using PracticaMvcCore2.Filters;
using PracticaMvcCore2.Models;
using PracticaMvcCore2.Repositories;
using System.Data;

namespace PracticaMvcCore2.Controllers
{
    public class LibrosController : Controller
    {
        private RepositoryLibros repo;

        public LibrosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {

            List<Libro> libros = await this.repo.GetLibrosAsync();
            return View(libros);

        }
        public async Task<IActionResult> LibrosGenero(int idgenero)
        {
            List<Libro> librosGen = await this.repo.GetLibrosGeneroAsync(idgenero);
            return View(librosGen);

        }

        public async Task<IActionResult> Details(int idlibro)
        {

            Libro libro = await this.repo.GetDetailsLibroAsync(idlibro);

            return View(libro);
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Carrito(int? idadded)
        {
            if (idadded != null)
            {
                List<Libro> librosCarrito;
                if (HttpContext.Session.GetObject<List<Libro>>("CARRITO") == null)
                {
                    librosCarrito = new List<Libro>();
                }
                else
                {
                    librosCarrito = HttpContext.Session.GetObject<List<Libro>>("CARRITO");
                }
                Libro libro = await this.repo.GetDetailsLibroAsync(idadded.Value);
                librosCarrito.Add(libro);
                HttpContext.Session.SetObject("CARRITO", librosCarrito);
            }

            return RedirectToAction("Index");
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> VerCarrito(int? ideliminar)
        {
            List<Libro> listaLibros = HttpContext.Session.GetObject<List<Libro>>("CARRITO");

            if (ideliminar != null)
            {
                Libro libro = listaLibros.Find(z => z.IdLibro == ideliminar.Value);

                listaLibros.Remove(libro);

                if (listaLibros.Count == 0)
                {

                    HttpContext.Session.Remove("CARRITO");

                }
                else
                {
                    //almacenamos de nuevo los datos en session
                    HttpContext.Session.SetObject("CARRITO", listaLibros);
                }

            }
            listaLibros = HttpContext.Session.GetObject<List<Libro>>("CARRITO");

            return View(listaLibros);
        }
        [AuthorizeUsuarios]
        public IActionResult PerfilUsuario()
        {
            return View();
        }

        [AuthorizeUsuarios]

        public async Task<IActionResult> Pedidos()
        {
            int idUsuario = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);

            List<VistaPedidos> pedidos = this.repo.GetVistaPedidoUsuario(idUsuario);

            return View(pedidos);

        }

        [AuthorizeUsuarios]

        public async Task<IActionResult> FinalizarCompra()
        {
            List<Libro> carrito = HttpContext.Session.GetObject<List<Libro>>("CARRITO");
            if (carrito != null)
            {
                int idUser = int.Parse(HttpContext.User.FindFirst("IdUsuario").Value);
                this.repo.InsertarPedido(carrito,idUser);
                HttpContext.Session.Remove("CARRITO");
                return RedirectToAction("Pedidos");
            }
            else
            {
                ViewData["MENSAJE"] = "No puedes comprar nada";
            }
            return View("Pedidos");

        }
    }
}

PracticaMvcCore2Iniciales/Views/Libros/Details.cshtml
@model PracticaMvcCore2.Models.Libro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdLibro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdLibro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editorial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editorial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Portada)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/@Html.DisplayFor(model => model.Portada)" style="height: 150px; width:100px" />

        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resumen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resumen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio) €
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdGenero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdGenero)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

<a asp-controller="Libros" asp-action="Carrito" asp-route-idadded="@Model.IdLibro" class="btn btn-dark">Añadir al carrito</a>

PracticaMvcCore2Iniciales/Views/Libros/FinalizarCompra.cshtml
<h1>Compra realizada</h1>

PracticaMvcCore2Iniciales/Views/Libros/Index.cshtml
@model IEnumerable<PracticaMvcCore2.Models.Libro>

@{
    ViewData["Title"] = "Index";

}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Portada)
            </th>
            <th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                    <img src="~/images/@Html.DisplayFor(modelItem => item.Portada)" style="height: 150px; width:100px" />
                
            </td>
            <td>
                    @Html.ActionLink("Details", "Details", new { idlibro = item.IdLibro }) |
            </td>
        </tr>
}
    </tbody>
</table>

PracticaMvcCore2Iniciales/Views/Libros/LibrosGenero.cshtml
@model IEnumerable<PracticaMvcCore2.Models.Libro>


<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Portada)
            </th>
            <th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    <img src="~/images/@Html.DisplayFor(modelItem => item.Portada)" style="height: 150px; width:100px" />

                </td>
                <td>
               
                    @Html.ActionLink("Details", "Details", new { idlibro = item.IdLibro }) ||

                </td>
            </tr>
        }
    </tbody>
</table>

PracticaMvcCore2Iniciales/Views/Libros/Pedidos.cshtml
@model IEnumerable<PracticaMvcCore2.Models.VistaPedidos>

@{
    ViewData["Title"] = "Pedidos";
}

<h1>Pedidos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdVistaPedidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Portada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioFinal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdVistaPedidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Portada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioFinal)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

PracticaMvcCore2Iniciales/Views/Libros/PerfilUsuario.cshtml
@using System.Security.Claims

<img src='~/images/@Context.User.FindFirst("Foto").Value' style="width: 150px; height:150px;"/>
<h1>Nombre : @Context.User.Identity.Name</h1>
<h2>Apellidos: @Context.User.FindFirst("Apellidos")</h2>
<h2>Email: @Context.User.FindFirst("Email")</h2>

PracticaMvcCore2Iniciales/Views/Libros/VerCarrito.cshtml
@using PracticaMvcCore2.Models
@{

    List<Libro>libroslista = Context.Session.GetObject<List<Libro>>("CARRITO");
}


@{
    ViewData["Title"] = "VerCarrito";
}

<h1>VerCarrito</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@if (libroslista != null)

{
    <table class="table">
        <thead>
            <tr>
                <th>
                    TITULO
                </th>
                <th>
                    PORTADA
                </th>
                <th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var li in libroslista)
            {
                <tr>
                    <td>
                        @li.Titulo
                    </td>
                    <td>
                        <img src="~/images/@Html.DisplayFor(modelItem => li.Portada)" style="height: 150px; width:100px" />

                    </td>
                    <td>
                        <a asp-controller="Libros" asp-action="VerCarrito" asp-route-ideliminar="@li.IdLibro" class="btn btn-dark">Eliminar del carrito</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a asp-controller="Libros" asp-action="FinalizarCompra" class="btn btn-dark">Realizar compra</a>

}
else
{
    
   <h2>No hay libros en el carrito</h2>
}